server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # API Proxy (optional but recommended to avoid CORS issues if they weren't configured inside backend)
    # We aren't strictly proxying because backend allows all CORS right now.
}
