def build_anomaly_prompt(context: dict) -> str:
    return (
        "You are an expert SRE for a subway monitoring system. "
        "Analyze the provided metrics and output JSON only.\n\n"
        "Rules:\n"
        "- Prioritize: API error surge > traffic spike > scheduler failures > train delays.\n"
        "- If off-hours, only analyze traffic anomalies and ignore others.\n"
        "- Use Korean for titles and summaries.\n"
        "- Output must be valid JSON with no markdown.\n\n"
        "Required JSON schema:\n"
        "{\n"
        "  \"overall_status\": \"정상|주의|위험\",\n"
        "  \"today_anomaly_count\": number,\n"
        "  \"latest_anomaly\": {\n"
        "    \"occurred_at\": \"ISO-8601\",\n"
        "    \"title\": string,\n"
        "    \"severity\": \"info|warning|critical\",\n"
        "    \"summary\": string\n"
        "  },\n"
        "  \"insights\": [\n"
        "    {\"title\": string, \"summary\": string}\n"
        "  ],\n"
        "  \"anomalies\": [\n"
        "    {\"severity\": \"info|warning|critical\", \"title\": string, \"occurred_at\": \"ISO-8601\", \"category\": string}\n"
        "  ],\n"
        "  \"selected_anomaly_detail\": {\n"
        "    \"title\": string,\n"
        "    \"occurred_at\": \"ISO-8601\",\n"
        "    \"description\": string,\n"
        "    \"evidence\": [string],\n"
        "    \"recommended_actions\": [string]\n"
        "  },\n"
        "  \"metric_trend\": {\n"
        "    \"label\": string,\n"
        "    \"points\": [{\"ts\": \"ISO-8601\", \"value\": number}]\n"
        "  }\n"
        "}\n\n"
        f"Context:\n{context}"
    )
