input {
  tcp {
    port => 50000
    codec => json_lines
  }
}

filter {
  # Add timestamp and other common fields if needed, 
  # but logback encoder already sends a well-structured JSON.
  mutate {
    remove_field => [ "port", "host" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "subway-logs-%{+YYYY.MM.dd}"
  }
  # For debugging in logstash console container
  stdout { codec => rubydebug }
}
